services:
  expressapp:
    image: ghcr.io/alexispet/final-test-maximedan/express:latest
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/post" ]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s
    ports:
      - "80:3000"
    depends_on:
      db:
        condition: service_healthy
    command: [ "npm", "run", "start" ]
    networks:
      - frontend
      - prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # - "traefik.enable=true"
      # - "traefik.http.routers.maxdanprod.rule=Host(`maxime.alpex.ovh`)"
      # - "traefik.http.routers.maxdanprod.entrypoints=websecure"
      # - "traefik.http.routers.maxdanprod.tls.certresolver=myresolver"

  db:
    image: mariadb:11.2.2
    environment:
      MARIADB_ROOT_PASSWORD: yes
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./docker/mariadb/data:/var/lib/mariadb"
    networks:
      - prod
    healthcheck:
      test: '/usr/bin/mariadb --user=${DB_USER} --password=${DB_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s

networks:
  frontend:
    external: true
    name: custom_frontend
  prod: