services:
  expressapp:
    image: ghcr.io/alexispet/final-test-maximedan/express:develop
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/post" ]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s
    depends_on:
      db:
        condition: service_healthy
    command: [ "npm", "run", "start" ]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: mariadb:11.2.2
    environment:
      MARIADB_ROOT_PASSWORD: yes
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./docker/mariadb/data:/var/lib/mariadb"
    ports:
      - 3306:3306
    healthcheck:
      test: '/usr/bin/mariadb --user=${DB_USER} --password=${DB_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s

