name: Lighthouse CI
on:
  schedule:
    - cron: '*/5 * * * *' # This will run the workflow every 5 minutes

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v10
        with:
            urls: |
                ${{ vars.APP_URL }}
            uploadArtifacts: true
            temporaryPublicStorage: true